apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    type: frontend
  ports:
  # service port (communication with container)
  - port: 81
    name: http-service
    # application port inside container
    targetPort: 80
    #external port 
    nodePort: 30100
  type: NodePort
