apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      app: webapp
  replicas: 2